### ISSUE TITLE
Проблема множественной перерисовки DOM

### ISSUE THREAD

**Issue by hydra13** [paradoxalyty/homeworks#1]
https://github.com/paradoxalyty/homeworks/blob/cb1a4987c165552d0d96227ad1d5a82e90960c52/homework%201/script.js#L33

В данном случае будет часто вызываться очень дорогостоящая операция перерисовки DOM. На мой взгляд лучше сначала все сложить в строку, а потом ее добавить на html единожды.

**Comment by paradoxalyty** [comment]
Спасибо за совет - исправлю.
В первый раз слышу, что перерисовка DOM дорогостоящая операция.
